return {
	PlaceObj('ModItemCode', {
		'CodeFileName', "Code/Script.lua",
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "options_chance_lcfya",
		'DisplayName', "Daily chance of outpost attack (%)",
		'Help', "Default is 20",
		'DefaultValue', "20",
		'ChoiceList', {
			"Off",
			"3",
			"5",
			"7",
			"10",
			"15",
			"20",
			"25",
			"33",
			"50",
			"66",
			"75",
			"100",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "options_cooldown_lcfya",
		'DisplayName', "Days between attacks (per outpost)",
		'Help', "1 means an attack is possible every day, 2 means once every 2 days, etc.",
		'DefaultValue', "1",
		'ChoiceList', {
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"14",
			"30",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "options_chance_wild_lcfya",
		'DisplayName', "Daily chance of wilderness attack (%)",
		'Help', "Default is 10",
		'DefaultValue', "10",
		'ChoiceList', {
			"Off",
			"3",
			"5",
			"7",
			"10",
			"15",
			"20",
			"25",
			"33",
			"50",
			"66",
			"75",
			"100",
		},
	}),
	PlaceObj('ModItemOptionChoice', {
		'name', "options_cooldown_wild_lcfya",
		'DisplayName', "Days between wilderness attacks (per region)",
		'Help', "1 means an attack is possible every day, 2 means once every 2 days, etc.",
		'DefaultValue', "2",
		'ChoiceList', {
			"1",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"14",
			"30",
		},
	}),
}